# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_optimal_filter <- function(pvalues, covariates, threshold) {
    .Call('_oiff_find_optimal_filter', PACKAGE = 'oiff', pvalues, covariates, threshold)
}

