# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_optimal_filter <- function(pvalues, covariates, threshold, larger) {
    .Call('_oiff_find_optimal_filter', PACKAGE = 'oiff', pvalues, covariates, threshold, larger)
}

find_optimal_filter_subsample <- function(pvalues, covariates, threshold, larger, subsample_proportion, num_iterations, random_seed, num_threads) {
    .Call('_oiff_find_optimal_filter_subsample', PACKAGE = 'oiff', pvalues, covariates, threshold, larger, subsample_proportion, num_iterations, random_seed, num_threads)
}

